- name: install java
  yum: name=java-1.8.0-openjdk-devel

- name: install repo
  raw: wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo

- name: install maven
  yum: name=apache-maven

- name: set JAVA_HOME
  raw: export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk