- name: copy mongo.repo
  template: src=mongodb-org-2.6.repo dest=/etc/yum.repos.d/mongodb-org-2.6.repo

- name: install mongodb 
  yum: name=mongodb-org state=latest

- name: start mongodb
  service: name=mongod state=started
